### ISSUE TITLE
Python app issue, 

### ISSUE THREAD

**Issue by xenexis** [arora-r/chatapp-with-voice-and-openai#1]
Hi,

Trying to test without docker , "pip install -r requirements.txt " runs fine, "python server.py" starts the server on localhost but show errors when I try to use it : 

`chatapp-with-voice-and-openai enexis$ sudo python3 server.py
Password:
 * Serving Flask app 'server'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://192.168.xx.248:8000
Press CTRL+C to quit
127.0.0.1 - - [01/Feb/2023 12:58:52] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Feb/2023 12:58:52] "GET /static/style.css HTTP/1.1" 304 -
127.0.0.1 - - [01/Feb/2023 12:58:52] "GET /static/script.js HTTP/1.1" 304 -

user_message who are you?
voice default
prompt: "Act like a personal assistant. You can respond to questions, translate sentences, summarize news, and give recommendations. who are you?"
openai response: {
  "choices": [
    {
      "finish_reason": "stop",
      "index": 0,
      "logprobs": null,
      "text": "\n\nMy name is AVA, I'm your virtual assistant. I'm here to help you with any number of tasks, from translating sentences to summarizing news to giving recommendations. Please let me know how I can be of assistance."
    }
  ],
  "created": 1675249153,
  "id": "cmpl-6f57Za10xivRPvxQ7YRFflQLmxbV6",
  "model": "text-davinci-003",
  "object": "text_completion",
  "usage": {
    "completion_tokens": 48,
    "prompt_tokens": 27,
    "total_tokens": 75
  }
}
[2023-02-01 12:59:16,812] ERROR in app: Exception on /process-message [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x104662770>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=1081): Max retries exceeded with url: /text-to-speech/api/v1/synthesize?output=output_text.wav (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104662770>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/enexis/Work/openai/chatapp-with-voice-and-openai/server.py", line 44, in process_prompt_route
    openai_response_speech = text_to_speech(openai_response_text, voice)
  File "/Users/enexis/Work/openai/chatapp-with-voice-and-openai/worker.py", line 36, in text_to_speech
    response = requests.post(api_url, headers=headers, json=json_data)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=1081): Max retries exceeded with url: /text-to-speech/api/v1/synthesize?output=output_text.wav (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104662770>: Failed to establish a new connection: [Errno 61] Connection refused'))
127.0.0.1 - - [01/Feb/2023 12:59:16] "POST /process-message HTTP/1.1" 500 -`

Of course I have updated the openai.api_key value in worker.py ...

Any idea ?

Thanks,

**Comment by arora-r** [comment]
Hey xenexis,

Thank you for playing around with the project!

I see that the `openai` key is set just fine, as the output shows a response from it as expected. Based off the error it looks like its trying to connect to `localhost:1081` and fails to do so. So, its probably a networking issue between pods/applications.

Might need to switch the base URLs for the tts and stt to be `http://host.docker.internal:1081` and `http://host.docker.internal:1080` respectively (in the `worker.py` file).

I just want to confirm that you're running the text-to-speech container on `localhost:1081`?

> ### Starting the TTS container
> 
> Remember to be in the correct directory - always be in the directory for the associated Dockerfile.
> 
> In a new terminal run the following commands. If you wish to run the image in the background you can add the `-d` option after `docker run`. Running the image in the background, allows you to continue using this terminal and does not show the logs of the container in the terminal.
> 
> ```sh
> cd models/tts # assuming you are in the root directory of this repository
> docker build . -t tts-standalone # this will take a while, you can do other things outside of this terminal while you wait
> docker run --rm -it --env ACCEPT_LICENSE=true --publish 1081:1080 tts-standalone # this runs the image in the foreground
> ```
> 
> Now update the `base_url` value in the `workey.py` file for the `text_to_speech` function to `http://localhost:1081`
> 
> ### Starting the STT container
> 
> Remember to be in the correct directory - always be in the directory for the associated Dockerfile.
> 
> In a new terminal run the following commands. If you wish to run the image in the background you can add the `-d` option after `docker run`. Running the image in the background, allows you to continue using this terminal and does not show the logs of the container in the terminal.
> 
> ```sh
> cd models/stt # assuming you are in the root directory of this repository
> docker build . -t stt-standalone # this will take a while, you can do other things outside of this terminal while you wait
> docker run --rm -it --env ACCEPT_LICENSE=true --publish 1080:1080 stt-standalone # this runs the image in the foreground
> ```
> 
> Now update the `base_url` value in the `workey.py` file for the `speech_to_text` function to `http://localhost:1080`

To enable voice interaction, this project requires 2 other containers running simultaneously, the Text to Speech container and Speech to Text container. I should probably add a `docker-compose` file to make deployment by Docker easier 😂 .

Please let me know if that is not the case though.

**Comment by arora-r** [comment]
Hey @xenexis,

I created a `docker-compose.yml` file. Can you test the new instructions and let me know if you still face this issue (or any others)?

Thanks in advance!

**Comment by xenexis** [comment]
Hi arora-r,

Indeed the first issue was due to IBM app , have tested again with the new instructions and seems to be working like a charm!
Thank you for your work and can confirm its a exciting (and quick) way to test the AI and personal assistant.
